<?php View::content() ?>
<?php echo Form::open("","POST","id='form-coordinacion'") ?>
  <div class="form-group">
    <label for="exampleInputEmail1">Departamento</label>
    <?php echo Form::dbselect("coordinacion.departamento_id",null,null,"Departamento","class='form-control' readonly") ?>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Coordinacion</label>
    <?php echo Form::text("coordinacion.nombre","class='form-control'") ?>
  </div>
  <button type="submit" class="btn btn-default">Agregar</button>
</form>
<script type="text/javascript">
	$(document).ready(function(){
		$(document).one("submit","#form-coordinacion",function(){
			var data = $(this).serialize();
			$.ajax({
				url:"../coordinacion/nueva",
				data:data,
				dataType:"json",
				async:false,
				type:"post",
				success:function(r){
					console.log(r)
					if (r.correcto) {
						alert(r.mensaje);
						id_departamento = $("#coordinacion_departamento_id option:selected").val();
						$('#myModal').modal('toggle')
						$.ajax({
							async:false,
							url:"../coordinacion/get/"+id_departamento,
							success:function(r2){
								$("#asignacion_coordinacion_id").html(r2)
							}
						})
					}else{
						alert(r.mensaje);
					}
				}
			});
			return false;
		})
	})
</script>