<?php View::content() ?>
<h3>Equipos</h3>
<?php echo Tag::css("datatable/css/datatable.bootstrap"); ?>
<?php echo Tag::js("datatable/js/jquery.dataTables"); ?>
<?php echo Tag::js("datatable/js/datatable.bootstrap"); ?>
<script type="text/javascript">
	$(document).ready(function(){
		$(".table").DataTable({
			"language":{
			    "sProcessing":     "Procesando...",
			    "sLengthMenu":     "Mostrar _MENU_ registros",
			    "sZeroRecords":    "No se encontraron resultados",
			    "sEmptyTable":     "Ningún dato disponible en esta tabla",
			    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
			    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
			    "sInfoPostFix":    "",
			    "sSearch":         "Buscar:",
			    "sUrl":            "",
			    "sInfoThousands":  ",",
			    "sLoadingRecords": "Cargando...",
			    "oPaginate": {
			        "sFirst":    "Primero",
			        "sLast":     "Último",
			        "sNext":     "Siguiente",
			        "sPrevious": "Anterior"
			    },
			    "oAria": {
			        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
			        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
			    }
			}
		});
	})
</script>
<table class="datatable table">
	<thead>
		<th>Ip</th>
		<th>Macaddress 1</th>
		<th>Macaddress 2</th>
		<th>S.O</th>
	</thead>
	<?php foreach ($equipos as $key => $value): ?>
		<tr>
			<td><?php echo $value->ip ?></td>
			<td><?php echo $value->macaddress1 ?></td>
			<td><?php echo $value->macaddress12 ?></td>
			<td><?php echo $value->so ?></td>
		</tr>
	<?php endforeach ?>
</table>