
<?php View::content() ?>
<?php echo Form::open("","POST","id='form-case'") ?>
    <div class="col-sm-5 form-group">
        <label for="">Tipo</label>
        <?php echo Form::text("cases.tipo","class='form-control' placeholder='Tipo  ..'") ?>
    </div>
    <div class="col-sm-5 form-group">
        <label for="">Marca</label>
        <?php echo Form::text("cases.marca","class='form-control' placeholder='Marca (Micronics,Delux ..)'") ?>
    </div>
    <div class="col-sm-5 form-group">
        <label for="">Modelo</label>
        <?php echo Form::text("cases.modelo","class='form-control' placeholder='Modelo ..'") ?>
    </div>
    <div class="col-sm-5 form-group">
        <label for="">serial</label>
        <?php echo Form::text("cases.serial","class='form-control' placeholder='serial (123123,1231f2..)'") ?>
    </div>
    <div style="clear:both"></div>
    <input type="submit" value="Guardar"class="btn btn-default">
</form>
<script type="text/javascript">
    $(document).ready(function(){
        $(document).one("submit","#form-case",function(){
            var data = $(this).serialize();
            $.ajax({
                url:"../case/nuevo",
                type:"POST",
                data:data,
                async:false,
                success:function(r){
                    if (r.correcto) {
                        alert(r.mensaje);
                        $('#myModal').modal('toggle')
                        $.ajax({
                            url:"../case/get",
                            async:false,
                            success:function(r){
                    
                                $("#equipo_cases_id").html(r);
                            }
                        })
                    }else{
                        alert(r.mensaje)
                    }
                }
            })
            return false;
        })
    })
</script>