<?php View::content() ?>
<?php echo Form::open("","POST","id='form-departamento'") ?>
  <div class="form-group">
    <label for="exampleInputPassword1">Departamento</label>
    <?php echo Form::text("departamento.nombre","class='form-control'") ?>
  </div>
	<div class="form-group">
    <label for="exampleInputPassword1">Descripcion</label>
    <?php echo Form::textarea("departamento.descripcion","class='form-control'") ?>
  </div>

  <button type="submit" class="btn btn-default">Agregar</button>
</form>
<script type="text/javascript">
	$(document).ready(function(){
		$(document).one("submit","#form-departamento",function(){
			var data = $(this).serialize();
			$.ajax({
				url:"../departamento/nuevo",
				data:data,
				dataType:"json",
				async:false,
				type:"post",
				success:function(r){
					console.log(r)
					if (r.correcto) {
						alert(r.mensaje);
						$('#myModal').modal('toggle')
						$.ajax({
							async:false,
							url:"../departamento/get/",
							success:function(r2){
								$("#asignacion_departamento_id").html(r2)
							}
						})
					}else{
						alert(r.mensaje);
					}
				}
			});
			return false;
		})
	})
</script>