<?php View::content() ?>
<h2>Nuevo</h2>
<?php echo Form::open() ?>
  <div class="form-group">
  	<div class="col-sm-5">
	    <label for="">Departamento</label>
	    <?php echo Form::dbselect("asignacion.departamento_id",null,null,"Departamento","class='form-control'") ?>
	    <a href="#" data-toggle="modal" class="modales" data-target="#myModal">Nuevo Departamento</a>
    </div>
    <div class="col-sm-5">
	    <label for="">Coordinacion</label>
	    <?php echo Form::select("asignacion.coordinacion_id",array("Coordinacion"),"class='form-control'") ?>
	    <a href="#" data-toggle="modal" class="modales" data-target="#myModal">Nueva Coordinacion</a>
    </div>
    <div style="clear:both"></div>
    <br>
    <fieldset>
	    	<legend>Datos de Equipo</legend>
	    <div class="col-sm-5">
		    <label for="">Nombre Equipo</label>
		    <?php echo Form::text("equipo.nombre","class='form-control' placeholder='Nombre Equipo'") ?>
	    </div>
	    <div class="col-sm-5">
		    <label for="">Sistem Operativo</label>
		    <?php echo Form::text("equipo.so","class='form-control' placeholder='Sistem Operativo'") ?>
	    </div>
	    <div style="clear:both"></div>
	    <div class="col-sm-5">
		    <label for="">Bien Nacional</label>
		    <?php echo Form::text("equipo.biennacional","class='form-control' placeholder='Bien Nacional'") ?>
	    </div>
	    <div class="col-sm-5">
		    <label for="">IP</label>
		    <?php echo Form::text("equipo.ip","class='form-control' placeholder='IP'") ?>
	    </div>
	    <div style="clear:both"></div>
	    <div class="col-sm-5">
		    <label for="">MacAddress (Lan)</label>
		    <?php echo Form::text("equipo.macaddress","class='form-control' placeholder='MacAddress (Lan)'") ?>
	    </div>
	    <div class="col-sm-5">
		    <label for="">MacAddress (inalambrico)</label>
		    <?php echo Form::text("equipo.macaddress2","class='form-control' placeholder='MacAddress (inalambrico)'") ?>
	    </div>
	    <div style="clear:both"></div>
    </fieldset>
    <br>
    <fieldset>
    	<div class="form-group">
    		<legend>Procesador</legend>
    		<?php echo Form::select("equipo.procesador_id",$procesadores,"class='form-control'") ?>
    	</div>
   		<a href="#" data-toggle="modal" class="modales" data-target="#myModal">Nuevo Procesador</a>
    </fieldset>
    <br>
    <fieldset>
    	<div class="form-group">
    		<legend>Ram</legend>
    		<?php echo Form::select("equipo.ram_id",$rams,"class='form-control'") ?>
    	</div>
   		<a href="#" data-toggle="modal" class="modales" data-target="#myModal">Nueva Ram</a>
    </fieldset>
  </div>
  
  <input type="submit" class="btn btn-success" value="Guardar">
</form>




<!-- modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
	$(document).ready(function(){
		$('.modales').click(function(e){
			e.preventDefault();
			var nombre = $(this).text();
			if (nombre == 'Nuevo Departamento') {
				$( ".modal-body" ).load( "../departamento/nuevo", function() {
				  console.log( "Load was performed." );
				});
			}
			if (nombre == 'Nueva Coordinacion') {
				departamento_id = $("#asignacion_departamento_id option:selected").val();
				if (departamento_id) {
					$( ".modal-body" ).load( "../coordinacion/nueva/"+departamento_id, function() {
					  console.log( "Load was performed." );
					});
				}else{
					$( ".modal-body" ).html("<p class='alert alert-warning'>Es necesario Elegir un Departamento para agregar una coordinacion</p>")
				}
			}
			if (nombre == 'Nuevo Procesador') {			
				$( ".modal-body" ).load( "../procesador/nuevo/", function() {
				  console.log( "Load was performed." );
				});
			}
			if (nombre == 'Nueva Ram') {			
				$( ".modal-body" ).load( "../ram/nueva/", function() {
				  console.log( "Load was performed." );
				});
			}
			$(".modal-title").text(nombre);
		})
		$("#asignacion_departamento_id").change(function(){
			departamento_id = $("#asignacion_departamento_id option:selected").val();
			$.get("../coordinacion/get/"+departamento_id,function(r){

				$("#asignacion_coordinacion_id").html(r);
			})
		})
	})
</script>